apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment-3-{{ .Values.container.name }}
  namespace: {{ .Values.container.namespace }}
  labels:
    app: {{ .Values.container.name }}
    areanegocio: tecnologia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      containers:
        - name: contenedor-principal
          image: fabricioph2/curso:build-{{ .Values.container.tag }}  # <-- Reemplaza con la imagen que quieras usar
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"